### ISSUE TITLE
Dead Project, no documentation, but seems to work.

### ISSUE THREAD

**Issue by FranciscoKnebel** [asengupta/BPlusTree#2]
Easy enough to get it working, but absolute zero documentation in code.
If I have time, i'll fork this with commentaries. Hard to find a working B-tree implementation in C# here.

**Comment by introspection3** [comment]
document............

**Comment by FranciscoKnebel** [comment]
Hey, this repo never went active again, so I found this other implementation which worked better:
https://github.com/markmeeus/btree-dotnet

**Comment by introspection3** [comment]
@FranciscoKnebel thx.
